// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVARYF2ikrhgnv_qZkaqW9YG94Kz6K3w',
    appId: '1:156340334899:web:fac9d6b9f5d3a6cf08ce46',
    messagingSenderId: '156340334899',
    projectId: 'event-management-af69d',
    authDomain: 'event-management-af69d.firebaseapp.com',
    storageBucket: 'event-management-af69d.appspot.com',
    measurementId: 'G-09LTLYMBY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG5O_nDG2mdPoigVPYTOsDyewBTDzBWf4',
    appId: '1:156340334899:android:36b912a7c9c419a708ce46',
    messagingSenderId: '156340334899',
    projectId: 'event-management-af69d',
    storageBucket: 'event-management-af69d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6ejfQ0dvjK1Ip7LekPF-7a2eEArTjNo',
    appId: '1:156340334899:ios:2a2b218c4c94133908ce46',
    messagingSenderId: '156340334899',
    projectId: 'event-management-af69d',
    storageBucket: 'event-management-af69d.appspot.com',
    iosBundleId: 'com.example.eventManagementFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6ejfQ0dvjK1Ip7LekPF-7a2eEArTjNo',
    appId: '1:156340334899:ios:0c9d4735a93fe2b108ce46',
    messagingSenderId: '156340334899',
    projectId: 'event-management-af69d',
    storageBucket: 'event-management-af69d.appspot.com',
    iosBundleId: 'com.example.eventManagementFirebase.RunnerTests',
  );
}
